### ISSUE TITLE
Importing model to Ollama.

### ISSUE THREAD

**Issue by sinanugur** [ltgoslo/norallm#1]
Hi, 

I want to import the model (e.g.  normistral-7b-warm ) into ollama. 

I got that but when I query with the example "I'm super excited about this Norwegian NORA model! Can it translate these sentences?", the model generates random sentences in Norwegian.

Is there a Modelfile for ollama.

Cheers,
@sinanugur

**Comment by davda54** [comment]
Closed as a duplicate: https://huggingface.co/norallm/normistral-7b-warm/discussions/6
